name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit pytest
      - name: Lint with flake8
        run: flake8 .
      - name: Security Scan with bandit
        run: bandit -r .
      - name: Test with pytest
        run: pytest tests/

  scorecard:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: OSSF Scorecard action
        uses: ossf/scorecard-action@v2.4.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          results_file: results.sarif.json
          results_format: sarif
